<h2 style="color:green" align="center"> Machine Learning With Python: Linear Regression Multiple Variables</h2>

Below is the table containing home prices in monroe twp, NJ. Here price depends on **area (square feet), bed rooms and age of the home (in years)**. Given these prices we have to predict prices of new homes based on area, bed rooms and age.

<img src="homeprices.jpg" style='height:200px;width:350px'>

We will use regression with multiple variables here. Price can be calculated using following equation,

<img src="equation.jpg" >

Here area, bedrooms, age are called independant variables or **features** whereas price is a dependant variable

In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model
import math

In [2]:
df=pd.read_excel('home.xlsx')

In [3]:
df

area  bedroom  age   price
0  3000      4.0   15  565000
1  3200      NaN   18  610000
2  3600      3.0   30  595000
3  4000      5.0    8  760000
4  4100      6.0    8  810000
5  2600      3.0   20  550000

**Data Preprocessing: Fill NA values with median value of a column**

In [5]:
df.bedroom.median()

4.0

In [7]:
df.bedroom=df.bedroom.fillna(df.bedroom.median())
df

area  bedroom  age   price
0  3000      4.0   15  565000
1  3200      4.0   18  610000
2  3600      3.0   30  595000
3  4000      5.0    8  760000
4  4100      6.0    8  810000
5  2600      3.0   20  550000

In [8]:
df['bedroom'].describe()

count    6.000000
mean     4.166667
std      1.169045
min      3.000000
25%      3.250000
50%      4.000000
75%      4.750000
max      6.000000
Name: bedroom, dtype: float64

In [9]:
model=linear_model.LinearRegression()
model.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

**Find price of home with 2400 sqr ft area, 4 bedrooms, 5 year old**

In [10]:
model.predict([[2400,4,5]])

C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([567669.79329512])

**Find price of home with 3000 sqr ft area, 3 bedrooms, 10 year old**

In [12]:
model.predict([[3000,3,10]])

C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([595359.7888393])

In [14]:
model.coef_


array([  112.06244194, 23388.88007794, -3231.71790863])

In [15]:
model.intercept_

221323.00186540443